/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Samples
         * @description Paginated list of live samples (deleted_at IS NULL) with filters and
         *     intrinsic child-row counts (n_acquisitions/n_tomograms/n_tilt_series).
         *
         *     Filters are registry-driven (``catalog.api.filter_fields.FIELDS``); the
         *     full param set is read off ``request.query_params`` rather than declared
         *     one-by-one. Param naming: text/existence/boolean use the field ``key``;
         *     range fields use ``{key}_min`` / ``{key}_max``. See the OpenAPI-friendly
         *     note: the registry is the documented contract.
         *
         *     Filter semantics:
         *       * Repeatable categorical params act as OR within a facet, AND across.
         *       * Sub-entity (1:1, label, acquisition, annotation) filters use EXISTS
         *         subqueries; all conditions on one sub-entity must hold on the same row.
         *       * Range filters are NULL-tolerant: a row with NULL on the bound column is
         *         treated as a match (so partial metadata doesn't drop the whole sample).
         *       * Counts on the SELECT list are filter-INDEPENDENT total child rows.
         */
        get: operations["list_samples_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sample
         * @description Full sample record with typed sub-entities, acquisitions, tomograms,
         *     annotations, and tilt_series. 404 for missing or soft-deleted.
         */
        get: operations["get_sample_samples__sample_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Status/cadence card: latest scan, configured cadence, outstanding counts.
         */
        get: operations["get_summary_manage_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Outstanding Issues
         * @description Outstanding issues (resolved_at IS NULL), grouped by entity + file_kind.
         */
        get: operations["get_outstanding_issues_manage_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/issues/resolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resolved Issues
         * @description Issues resolved within the last ``within_hours`` hours, same grouping.
         */
        get: operations["get_resolved_issues_manage_issues_resolved_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/deletions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deletions
         * @description Append-only deletion feed, newest-first. No resolve/dismiss — every
         *     scan-detected disappearance stays in the feed (§08a).
         */
        get: operations["get_deletions_manage_deletions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_manage_scans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/scans/{scan_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_manage_scans__scan_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/scans/{scan_run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Logs
         * @description Log lines for one run, ordered by seq. 404 if the run is unknown.
         */
        get: operations["get_scan_logs_manage_scans__scan_run_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/scans/{scan_run_id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Samples
         * @description Per-sample outcomes for one run (optional outcome filter). 404 if unknown.
         */
        get: operations["get_scan_samples_manage_scans__scan_run_id__samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/samples/{sample_id}/warnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sample Warnings
         * @description Outstanding issues for this sample (current state).
         *
         *     Reads the entity-keyed ``issues`` table directly (resolved_at IS NULL)
         *     rather than the latest completed scan, so a sample skipped in the latest
         *     scan still surfaces its still-outstanding issues. Maps each issue to the
         *     legacy ``WarningOut`` shape used by the per-sample detail block.
         */
        get: operations["get_sample_warnings_samples__sample_id__warnings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extras/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Extras Summary
         * @description Group extras rows by (entity_type, key), most common first.
         */
        get: operations["extras_summary_extras_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filters/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Filter Options
         * @description Return distinct values + numeric ranges for the sample filter drawer.
         *
         *     All queries are scoped to live samples (``samples.deleted_at IS NULL``);
         *     soft-deleted samples never contribute to options or range bounds.
         */
        get: operations["get_filter_options_filters_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats Overview
         * @description Aggregate totals + per-project rollup over live samples.
         *
         *     ``totals.warnings`` reflects the current outstanding-issue count
         *     (``issues`` WHERE resolved_at IS NULL) — Plan §4.7.
         */
        get: operations["get_stats_overview_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tomograms/{sample_id}/{acquisition_id}/{reconstruction_alignment_id}/{tomogram_id}/preview.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tomogram Preview
         * @description Render the center-XY slice as a PNG (1200px wide, 1–99% percentile).
         *
         *     Returns 404 for missing row or path-outside-root, 422 for an existing
         *     row whose ``mrc_path`` is missing on disk.
         */
        get: operations["tomogram_preview_tomograms__sample_id___acquisition_id___reconstruction_alignment_id___tomogram_id__preview_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tomograms/{sample_id}/{acquisition_id}/{reconstruction_alignment_id}/{tomogram_id}/neuroglancer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tomogram Neuroglancer
         * @description Build a stateless Neuroglancer viewer URL for the tomogram.
         *
         *     No volume load, no in-process viewer: the returned URL points the
         *     Fileglancer-hosted Neuroglancer app at a ``precomputed://`` source served
         *     by mrc-server (``MRCNG_BASE_URL`` must resolve to the same data root, so
         *     ``row.mrc_path`` is the served relpath 1:1). Voxel size rides in mrc-server's
         *     ``info``; only the IMOD X/Y mirror and a 1-99 contrast window are baked into
         *     the state here.
         */
        post: operations["tomogram_neuroglancer_tomograms__sample_id___acquisition_id___reconstruction_alignment_id___tomogram_id__neuroglancer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotations/{sample_id}/{acquisition_id}/{reconstruction_alignment_id}/{annotation_id}/preview.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Annotation Preview
         * @description Render the annotation MRC's center-XY slice as a PNG (1200px, 1–99%).
         *
         *     Returns 404 for a missing row or path-outside-root, 422 for an annotation
         *     with no ``.mrc`` artifact.
         */
        get: operations["annotation_preview_annotations__sample_id___acquisition_id___reconstruction_alignment_id___annotation_id__preview_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annotations/{sample_id}/{acquisition_id}/{reconstruction_alignment_id}/{annotation_id}/neuroglancer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annotation Neuroglancer
         * @description Stateless Neuroglancer viewer URL for the annotation.
         *
         *     A bbox annotation (has a ``*_neuroglancer.json``) renders over a group
         *     tomogram served by mrc-ng-server, with the bbox baked into the URL as an
         *     inline ``local://annotations`` layer. A plain annotation renders its own
         *     ``.mrc``. Both go through the tomogram launch's precomputed path — no
         *     in-process viewer, so the frontend opens the URL as-is (see
         *     ``build_precomputed_launch_url``). 422 for an annotation with no artifact.
         */
        post: operations["annotation_neuroglancer_annotations__sample_id___acquisition_id___reconstruction_alignment_id___annotation_id__neuroglancer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acquisitions/{sample_id}/{acquisition_id}/polar.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Acquisition Polar
         * @description Semicircular polar plot of the acquisition's cached ``tilt_angles``.
         *
         *     422 if the acquisition has no cached angles.
         */
        get: operations["acquisition_polar_acquisitions__sample_id___acquisition_id__polar_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tilt-series/{sample_id}/{acquisition_id}/{tilt_series_id}/preview.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tilt Series Preview
         * @description Median-tilt image as PNG.
         *
         *     Prefers the authored ``Stack/`` (zarr, then ``.st``/``.mrc``); falls back
         *     to the acquisition's raw ``Frames/`` images. 422 if none are reachable.
         */
        get: operations["tilt_series_preview_tilt_series__sample_id___acquisition_id___tilt_series_id__preview_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tilt-series/{sample_id}/{acquisition_id}/{tilt_series_id}/neuroglancer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tilt Series Neuroglancer
         * @description Launch a Neuroglancer viewer over the tilt-series stack.
         *
         *     Prefer the authored ``Stack/`` (zarr, then ``.st``/``.mrc``); fall back to
         *     the acquisition's raw ``Frames/`` images. 422 if none are reachable.
         */
        post: operations["tilt_series_neuroglancer_tilt_series__sample_id___acquisition_id___tilt_series_id__neuroglancer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thumbnails/{relpath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thumbnail */
        get: operations["get_thumbnail_thumbnails__relpath__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toml/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Author Toml */
        post: operations["author_toml_toml__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toml/{kind}/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Toml
         * @description Seed mode: upload (ADR-0004). Parse a posted ``.toml`` body into form
         *     state with the backend ``tomllib`` loader — keeps TOML parsing off the
         *     frontend. Unknown/extra keys come through verbatim; the renderer splits
         *     registry fields from extras. Bad TOML -> 422 (no validation here; schema
         *     rules run on generate).
         */
        post: operations["parse_toml_toml__kind__parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toml/md-run-ids/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Md Run Ids
         * @description md_source.md_run_id suggestions: the ids of the sample's known md_runs.
         *     Free-text remains accepted on submit; this only feeds the dropdown.
         */
        get: operations["md_run_ids_toml_md_run_ids__sample_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toml/tilt-series-ids/{sample_id}/{acquisition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tilt Series Ids
         * @description Tilt-series ids in one acquisition, for the reconstruction form.
         *
         *     raw_tomogram.derived_from names a [[tilt_series]] in the acquisition's
         *     acquisition.toml — a different file, so the renderer's in-form cross-ref
         *     pooling cannot supply it.
         */
        get: operations["tilt_series_ids_toml_tilt_series_ids__sample_id___acquisition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toml/reconstruction-group-ids/{sample_id}/{acquisition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reconstruction Group Ids
         * @description Alignment-group folder names in one acquisition, for the reconstruction
         *     form's group selector.
         *
         *     One reconstruction.toml per Reconstructions/<group>/ folder, so the form
         *     needs the acquisition's group list to offer switching between them. The
         *     author route carries no sample context of its own, so it can't read the
         *     acquisition detail payload — hence this ids endpoint, mirroring
         *     /tilt-series-ids.
         */
        get: operations["reconstruction_group_ids_toml_reconstruction_group_ids__sample_id___acquisition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toml/{kind}/load/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load Toml
         * @description Seed mode: pull-from-API (ADR-0004). Load an existing record's authored
         *     fields for editing.
         *
         *     The DB reconstruction locates the record's on-disk directory (``path``, null
         *     if unknown). When the live ``{path}/{kind}.toml`` is readable under the data
         *     root, the form seeds from the *file* (fresh content) and its raw text is
         *     returned as ``baseline`` with ``source='disk'`` — the baseline lets a later
         *     "save to file share" refuse to clobber a file that changed since load
         *     (optimistic concurrency). When the file can't be read, load falls back to the
         *     catalog reconstruction (``source='catalog'``, ``baseline=None``) — this data
         *     may lag the on-disk file, so the renderer surfaces a staleness warning.
         *     ``path`` is always the directory to write back to.
         */
        get: operations["load_toml_toml__kind__load__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/md-previews/{relpath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Md Preview */
        get: operations["get_md_preview_md_previews__relpath__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquisitionOut */
        AcquisitionOut: {
            /** Acquisition Id */
            acquisition_id: string;
            /** Resolution */
            resolution?: number | null;
            /** Tilt Spacing */
            tilt_spacing?: number | null;
            /** Defocus Range */
            defocus_range?: string | null;
            /** Energy Filter */
            energy_filter?: string | null;
            /** Phase Plate */
            phase_plate?: boolean | null;
            /** Microscope */
            microscope?: string | null;
            /** Facility */
            facility?: string | null;
            /** Acquisition Quality */
            acquisition_quality?: number | null;
            /** Pixel Size */
            pixel_size?: number | null;
            /** Dose Per Tilt */
            dose_per_tilt?: number[] | null;
            /** Total Dose */
            total_dose?: number | null;
            /** Tilt Min */
            tilt_min?: number | null;
            /** Tilt Max */
            tilt_max?: number | null;
            /** Tilt Axis */
            tilt_axis?: number | null;
            /** Tilt Angles */
            tilt_angles?: number[] | null;
            /** Defocus Per Image */
            defocus_per_image?: number[] | null;
            /** Date Collected */
            date_collected?: string | null;
            /** Voltage */
            voltage?: number | null;
            /** Energy Filter Slit Width */
            energy_filter_slit_width?: number | null;
            /** Frame Count */
            frame_count?: number | null;
            /** Camera */
            camera?: string | null;
            /** Path */
            path?: string | null;
            md_source?: components["schemas"]["MdSourceOut"] | null;
            /**
             * Raw Tomograms
             * @default []
             */
            raw_tomograms: components["schemas"]["RawTomogramOut"][];
            /**
             * Post Processed Tomograms
             * @default []
             */
            post_processed_tomograms: components["schemas"]["PostProcessedTomogramOut"][];
            /**
             * Annotations
             * @default []
             */
            annotations: components["schemas"]["AnnotationOut"][];
            /**
             * Tilt Series
             * @default []
             */
            tilt_series: components["schemas"]["TiltSeriesOut"][];
            /**
             * Reconstruction Alignment
             * @default []
             */
            reconstruction_alignment: components["schemas"]["ReconstructionAlignmentOut"][];
            scan_status?: components["schemas"]["AcquisitionScanStatus"] | null;
        };
        /**
         * AcquisitionScanStatus
         * @description Per-acquisition freshness + thumbnail provenance (from
         *     ``acquisition_scan_status``). Extends the sample shape with the
         *     thumbnail's real rendered source, generated-at, and status.
         */
        AcquisitionScanStatus: {
            /** Last Scanned At */
            last_scanned_at: number;
            /** Last Changed At */
            last_changed_at?: number | null;
            /** Last Outcome */
            last_outcome: string;
            /** Last Scan Run Id */
            last_scan_run_id: string;
            /** Thumbnail Path */
            thumbnail_path?: string | null;
            /** Thumbnail Source Kind */
            thumbnail_source_kind?: string | null;
            /** Thumbnail Source Path */
            thumbnail_source_path?: string | null;
            /** Thumbnail Generated At */
            thumbnail_generated_at?: number | null;
            /** Thumbnail Status */
            thumbnail_status?: string | null;
        };
        /** AnnotationOut */
        AnnotationOut: {
            /** Annotation Id */
            annotation_id: string;
            /** Reconstruction Alignment Id */
            reconstruction_alignment_id: string;
            /** Type */
            type?: string | null;
            /** Derived From */
            derived_from?: string | null;
            /** Bounding Box */
            bounding_box?: string | null;
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /** ChromatinOut */
        ChromatinOut: {
            /** Substrate */
            substrate?: string | null;
            /** Linker Length Bp */
            linker_length_bp?: number | null;
            /** Linker Pattern */
            linker_pattern?: number[] | null;
            /** Linker Distribution */
            linker_distribution?: string | null;
            /** Buffer */
            buffer?: string | null;
            /** Ptm */
            ptm?: string | null;
            /** Histone Variants */
            histone_variants?: string | null;
            /** Transcription Factors */
            transcription_factors?: string | null;
            /** Nucleosome Count */
            nucleosome_count?: number | null;
            /** Dna Length Bp */
            dna_length_bp?: number | null;
            /** Nucleosome Um */
            nucleosome_uM?: number | null;
            /** Sequence Identity */
            sequence_identity?: string | null;
            /** Nucleosome Footprint */
            nucleosome_footprint?: number[] | null;
            /** Linker Length Fraction */
            linker_length_fraction?: number | null;
        };
        /**
         * DeletionEvent
         * @description One row of the append-only deletion audit feed (§08a/§08c).
         */
        DeletionEvent: {
            /** Id */
            id: number;
            /** Scan Run Id */
            scan_run_id: string;
            /** Detected At */
            detected_at: number;
            /** Entity Type */
            entity_type: string;
            /**
             * Kind
             * @default deletion
             */
            kind: string;
            /** Sample Id */
            sample_id: string;
            /** Acquisition Id */
            acquisition_id?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Last Known Path */
            last_known_path?: string | null;
            /** Last Known Json */
            last_known_json?: string | null;
        };
        /**
         * EntityScanStatus
         * @description Per-sample freshness rollup (from ``sample_scan_status``).
         */
        EntityScanStatus: {
            /** Last Scanned At */
            last_scanned_at: number;
            /** Last Changed At */
            last_changed_at?: number | null;
            /** Last Outcome */
            last_outcome: string;
            /** Last Scan Run Id */
            last_scan_run_id: string;
        };
        /** ExtrasSummaryRow */
        ExtrasSummaryRow: {
            /** Entity Type */
            entity_type: string;
            /** Key */
            key: string;
            /** Count */
            count: number;
        };
        /** FiducialOut */
        FiducialOut: {
            /** Aunp Size Nm */
            aunp_size_nm?: number | null;
            /** Vendor */
            vendor?: string | null;
            /** Catalog Number */
            catalog_number?: string | null;
            /** Product Name */
            product_name?: string | null;
            /** Concentration Value */
            concentration_value?: number | null;
            /** Concentration Unit */
            concentration_unit?: string | null;
        };
        /**
         * FiltersOptionsOut
         * @description Registry-driven filter options: ``categorical`` keyed by each ``text``
         *     field's key, ``ranges`` keyed by each ``range`` field's key.
         */
        FiltersOptionsOut: {
            /**
             * Categorical
             * @default {}
             */
            categorical: {
                [key: string]: string[];
            };
            /**
             * Ranges
             * @default {}
             */
            ranges: {
                [key: string]: components["schemas"]["RangeOut"];
            };
        };
        /** FreezingOut */
        FreezingOut: {
            /** Grid Type */
            grid_type?: string | null;
            /** Solution Type */
            solution_type?: string | null;
            /** Cryoprotectant */
            cryoprotectant?: string | null;
            /** Method */
            method?: string | null;
            /** Planchette Size */
            planchette_size?: string | null;
            /** Spacer Thickness */
            spacer_thickness?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IssueGroup
         * @description Outstanding (or recently-resolved) issues grouped by
         *     (scope, sample_id, acquisition_id, md_run_id, file_kind).
         */
        IssueGroup: {
            /** Scope */
            scope: string;
            /** Sample Id */
            sample_id?: string | null;
            /** Acquisition Id */
            acquisition_id?: string | null;
            /** Md Run Id */
            md_run_id?: string | null;
            /** File Kind */
            file_kind: string;
            /** File Path */
            file_path?: string | null;
            /** Severity */
            severity: string;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["IssueItem"][];
            /** First Seen At */
            first_seen_at: number;
            /** Last Seen At */
            last_seen_at: number;
            /** Last Seen Run Id */
            last_seen_run_id: string;
            /** Latest Run Id */
            latest_run_id?: string | null;
            /** Latest Scan At */
            latest_scan_at?: number | null;
            /** Resolved At */
            resolved_at?: number | null;
            /** Resolved Run Id */
            resolved_run_id?: string | null;
        };
        /** IssueItem */
        IssueItem: {
            /** Category */
            category: string;
            /** Message */
            message: string;
        };
        /** LabelOut */
        LabelOut: {
            /** Ordinal */
            ordinal: number;
            /** Label Target */
            label_target?: string | null;
            /** Aunp Type */
            aunp_type?: string | null;
            /** Aunp Size Nm */
            aunp_size_nm?: number | number[] | null;
            /** Conjugation */
            conjugation?: string | null;
            /** Conjugation Target */
            conjugation_target?: string | null;
            /** Fluorophore */
            fluorophore?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** LatestScanInfo */
        LatestScanInfo: {
            /** Started At */
            started_at: number;
            /** Ended At */
            ended_at?: number | null;
            /** Status */
            status: string;
            /** Duration */
            duration?: number | null;
        };
        /**
         * ManageSummary
         * @description Status/cadence card payload for the Manage page (§3.4).
         */
        ManageSummary: {
            latest_scan?: components["schemas"]["LatestScanInfo"] | null;
            /** Cadence Cron */
            cadence_cron: string;
            /** Cadence Tz */
            cadence_tz: string;
            outstanding: components["schemas"]["OutstandingCounts"];
            /**
             * Deletions Latest Run
             * @default 0
             */
            deletions_latest_run: number;
        };
        /** MdRunOut */
        MdRunOut: {
            /** Md Run Id */
            md_run_id: string;
            /** Seed */
            seed?: number | null;
            /** Computer */
            computer?: string | null;
            /** Sample Time */
            sample_time?: number | null;
            /** Timestep */
            timestep?: number | null;
            /** Reference Contact */
            reference_contact?: string | null;
            /** Force Field Version */
            force_field_version?: string | null;
            /** Preview Path */
            preview_path?: string | null;
        };
        /** MdSourceOut */
        MdSourceOut: {
            /** Md Run Id */
            md_run_id?: string | null;
            /** Frame */
            frame?: number | null;
        };
        /** MillingOut */
        MillingOut: {
            /** Scheme */
            scheme?: string | null;
            /** Date */
            date?: string | null;
            /** Quality */
            quality?: string | null;
        };
        /** OutstandingCounts */
        OutstandingCounts: {
            /**
             * Errors
             * @default 0
             */
            errors: number;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
        };
        /** PostProcessedTomogramOut */
        PostProcessedTomogramOut: {
            /** Tomogram Id */
            tomogram_id: string;
            /** Reconstruction Alignment Id */
            reconstruction_alignment_id: string;
            /** Voxel Size */
            voxel_size?: number | null;
            /**
             * Mrc Voxel Size Missing
             * @default false
             */
            mrc_voxel_size_missing: boolean;
            /** Image Size X */
            image_size_x?: number | null;
            /** Image Size Y */
            image_size_y?: number | null;
            /** Image Size Z */
            image_size_z?: number | null;
            /** Mrc Path */
            mrc_path?: string | null;
            /** Zarr Path */
            zarr_path?: string | null;
            /** Zarr Axes */
            zarr_axes?: string | null;
            /** Zarr Scale */
            zarr_scale?: number[] | null;
            /** Denoising Software */
            denoising_software?: string | null;
            /** Ctf Software */
            ctf_software?: string | null;
            /** Missing Wedge Software */
            missing_wedge_software?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /**
             * Derived From
             * @default []
             */
            derived_from: string[];
        };
        /** ProjectStatRow */
        ProjectStatRow: {
            /** Project */
            project: string;
            /**
             * Samples
             * @default 0
             */
            samples: number;
            /**
             * Acquisitions
             * @default 0
             */
            acquisitions: number;
            /**
             * Tomograms
             * @default 0
             */
            tomograms: number;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
        };
        /**
         * RangeOut
         * @description Range bounds; ``None`` when no rows exist for the facet.
         */
        RangeOut: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
        /** RawTomogramOut */
        RawTomogramOut: {
            /** Tomogram Id */
            tomogram_id: string;
            /** Reconstruction Alignment Id */
            reconstruction_alignment_id: string;
            /** Voxel Size */
            voxel_size?: number | null;
            /**
             * Mrc Voxel Size Missing
             * @default false
             */
            mrc_voxel_size_missing: boolean;
            /** Image Size X */
            image_size_x?: number | null;
            /** Image Size Y */
            image_size_y?: number | null;
            /** Image Size Z */
            image_size_z?: number | null;
            /** Mrc Path */
            mrc_path?: string | null;
            /** Zarr Path */
            zarr_path?: string | null;
            /** Zarr Axes */
            zarr_axes?: string | null;
            /** Zarr Scale */
            zarr_scale?: number[] | null;
            /** Pipeline */
            pipeline?: string | null;
            /** Software */
            software?: string | null;
            /** Derived From */
            derived_from?: string | null;
        };
        /** ReconstructionAlignmentOut */
        ReconstructionAlignmentOut: {
            /** Reconstruction Alignment Id */
            reconstruction_alignment_id: string;
            /** Alignment Software */
            alignment_software?: string | null;
            /** Alignment Method */
            alignment_method?: string | null;
            /**
             * Alignment Files
             * @default []
             */
            alignment_files: string[];
            /** Mtime */
            mtime?: number | null;
        };
        /** SampleDetail */
        SampleDetail: {
            /** Sample Id */
            sample_id: string;
            /** Project */
            project: string;
            /** Lab Name */
            lab_name?: string | null;
            /** Data Source */
            data_source: string;
            /** Type */
            type?: string | null;
            /** Cell Type */
            cell_type?: string | null;
            /** Description */
            description?: string | null;
            /** Path */
            path?: string | null;
            chromatin?: components["schemas"]["ChromatinOut"] | null;
            fiducial?: components["schemas"]["FiducialOut"] | null;
            simulation?: components["schemas"]["SimulationOut"] | null;
            freezing?: components["schemas"]["FreezingOut"] | null;
            milling?: components["schemas"]["MillingOut"] | null;
            /**
             * Label
             * @default []
             */
            label: components["schemas"]["LabelOut"][];
            /**
             * Md Run
             * @default []
             */
            md_run: components["schemas"]["MdRunOut"][];
            /**
             * Acquisitions
             * @default []
             */
            acquisitions: components["schemas"]["AcquisitionOut"][];
            /** Thumbnail Path */
            thumbnail_path?: string | null;
            scan_status?: components["schemas"]["EntityScanStatus"] | null;
        };
        /** SampleSummary */
        SampleSummary: {
            /** Sample Id */
            sample_id: string;
            /** Project */
            project: string;
            /** Lab Name */
            lab_name?: string | null;
            /** Data Source */
            data_source: string;
            /** Type */
            type?: string | null;
            /** Cell Type */
            cell_type?: string | null;
            /** Description */
            description?: string | null;
            /** Path */
            path?: string | null;
            /**
             * Warning Count
             * @default 0
             */
            warning_count: number;
            /**
             * N Acquisitions
             * @default 0
             */
            n_acquisitions: number;
            /**
             * N Tomograms
             * @default 0
             */
            n_tomograms: number;
            /**
             * N Tilt Series
             * @default 0
             */
            n_tilt_series: number;
            /** Thumbnail Path */
            thumbnail_path?: string | null;
            /** Md Preview Path */
            md_preview_path?: string | null;
        };
        /** ScanLogLine */
        ScanLogLine: {
            /** Id */
            id: number;
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /** Level */
            level: string;
            /** Sample Id */
            sample_id?: string | null;
            /** Message */
            message: string;
        };
        /** ScanRun */
        ScanRun: {
            /** Scan Run Id */
            scan_run_id: string;
            /** Started At */
            started_at: number;
            /** Ended At */
            ended_at?: number | null;
            /** Status */
            status: string;
            /** Root */
            root: string;
            /** N Upserted */
            n_upserted?: number | null;
            /** N Skipped */
            n_skipped?: number | null;
            /** N Failed */
            n_failed?: number | null;
            /** N New Issues */
            n_new_issues?: number | null;
            /** N Resolved Issues */
            n_resolved_issues?: number | null;
            /** N Warning Active */
            n_warning_active?: number | null;
            /** N Error Active */
            n_error_active?: number | null;
        };
        /** ScanSampleOutcomeOut */
        ScanSampleOutcomeOut: {
            /** Sample Id */
            sample_id: string;
            /** Outcome */
            outcome: string;
            /** Detail */
            detail?: string | null;
        };
        /** SimulationOut */
        SimulationOut: {
            /** Dataset Type */
            dataset_type?: string | null;
        };
        /** StatsOverviewOut */
        StatsOverviewOut: {
            totals: components["schemas"]["StatsTotalsOut"];
            /**
             * By Project
             * @default []
             */
            by_project: components["schemas"]["ProjectStatRow"][];
        };
        /** StatsTotalsOut */
        StatsTotalsOut: {
            /**
             * Samples
             * @default 0
             */
            samples: number;
            /**
             * Acquisitions
             * @default 0
             */
            acquisitions: number;
            /**
             * Tilt Series
             * @default 0
             */
            tilt_series: number;
            /**
             * Tomograms
             * @default 0
             */
            tomograms: number;
            /**
             * Annotations
             * @default 0
             */
            annotations: number;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
        };
        /** TiltSeriesOut */
        TiltSeriesOut: {
            /** Tilt Series Id */
            tilt_series_id: string;
            /** Derived From */
            derived_from?: string | null;
            /** Is Aligned */
            is_aligned?: boolean | null;
            /** Alignment Software */
            alignment_software?: string | null;
            /** Alignment Method */
            alignment_method?: string | null;
            /** St Path */
            st_path?: string | null;
            /** Zarr Path */
            zarr_path?: string | null;
            /**
             * Alignment Files
             * @default []
             */
            alignment_files: string[];
            /** Mtime */
            mtime?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ViewerLaunchOut
         * @description Response of a POST .../neuroglancer launch.
         *
         *     Frontend rewrites the hostname to ``window.location.hostname`` before
         *     opening.
         */
        ViewerLaunchOut: {
            /** Url */
            url: string;
        };
        /** WarningOut */
        WarningOut: {
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: string;
            /** Category */
            category: string;
            /** Location */
            location: string;
            /** Message */
            message: string;
            /** Detected At */
            detected_at: number;
            /** Scan Run Id */
            scan_run_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_samples_samples_get: {
        parameters: {
            query?: {
                q?: string | null;
                sort?: "sample_id" | "project" | "type";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_samples__sample_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_manage_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManageSummary"];
                };
            };
        };
    };
    get_outstanding_issues_manage_issues_get: {
        parameters: {
            query?: {
                severity?: ("error" | "warning") | null;
                file_kind?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resolved_issues_manage_issues_resolved_get: {
        parameters: {
            query?: {
                within_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deletions_manage_deletions_get: {
        parameters: {
            query?: {
                entity_type?: string | null;
                sample_id?: string | null;
                within_hours?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scans_manage_scans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRun"][];
                };
            };
        };
    };
    get_scan_manage_scans__scan_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_logs_manage_scans__scan_run_id__logs_get: {
        parameters: {
            query?: {
                level?: ("DEBUG" | "INFO" | "WARNING" | "ERROR") | null;
                q?: string | null;
            };
            header?: never;
            path: {
                scan_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanLogLine"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_samples_manage_scans__scan_run_id__samples_get: {
        parameters: {
            query?: {
                outcome?: ("upserted" | "skipped" | "failed") | null;
            };
            header?: never;
            path: {
                scan_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSampleOutcomeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_warnings_samples__sample_id__warnings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarningOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extras_summary_extras_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtrasSummaryRow"][];
                };
            };
        };
    };
    get_filter_options_filters_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersOptionsOut"];
                };
            };
        };
    };
    get_stats_overview_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverviewOut"];
                };
            };
        };
    };
    tomogram_preview_tomograms__sample_id___acquisition_id___reconstruction_alignment_id___tomogram_id__preview_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
                reconstruction_alignment_id: string;
                tomogram_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tomogram_neuroglancer_tomograms__sample_id___acquisition_id___reconstruction_alignment_id___tomogram_id__neuroglancer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
                reconstruction_alignment_id: string;
                tomogram_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewerLaunchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotation_preview_annotations__sample_id___acquisition_id___reconstruction_alignment_id___annotation_id__preview_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
                reconstruction_alignment_id: string;
                annotation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotation_neuroglancer_annotations__sample_id___acquisition_id___reconstruction_alignment_id___annotation_id__neuroglancer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
                reconstruction_alignment_id: string;
                annotation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewerLaunchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquisition_polar_acquisitions__sample_id___acquisition_id__polar_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tilt_series_preview_tilt_series__sample_id___acquisition_id___tilt_series_id__preview_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
                tilt_series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tilt_series_neuroglancer_tilt_series__sample_id___acquisition_id___tilt_series_id__neuroglancer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
                tilt_series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewerLaunchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumbnail_thumbnails__relpath__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relpath: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    author_toml_toml__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_toml_toml__kind__parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    md_run_ids_toml_md_run_ids__sample_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tilt_series_ids_toml_tilt_series_ids__sample_id___acquisition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconstruction_group_ids_toml_reconstruction_group_ids__sample_id___acquisition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
                acquisition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_toml_toml__kind__load__record_id__get: {
        parameters: {
            query?: {
                sample_id?: string | null;
                acquisition_id?: string | null;
            };
            header?: never;
            path: {
                kind: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_md_preview_md_previews__relpath__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relpath: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
