"""add info severity

Revision ID: 4fc5ee73fa34
Revises: 02915ef0dfac
Create Date: 2026-08-17 12:38:00.537806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc5ee73fa34'
down_revision: Union[str, Sequence[str], None] = '02915ef0dfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_info_active', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_column('n_info_active')

    # ### end Alembic commands ###
