"""add salt_mM to chromatin

Revision ID: 5db8dc9235b0
Revises: 72e3bbb2df2a
Create Date: 2026-07-23 15:43:08.966750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db8dc9235b0'
down_revision: Union[str, Sequence[str], None] = '72e3bbb2df2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromatin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt_mM', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chromatin', schema=None) as batch_op:
        batch_op.drop_column('salt_mM')

    # ### end Alembic commands ###
