"""add deletion_events table

Revision ID: 649ac31f8a2f
Revises: f8401280a106
Create Date: 2026-07-08 20:57:32.706927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649ac31f8a2f'
down_revision: Union[str, Sequence[str], None] = 'f8401280a106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('detected_at', sa.Float(), nullable=False),
    sa.Column('entity_type', sa.Enum('sample', 'acquisition', 'raw_tomogram', 'post_processed_tomogram', 'annotation', 'tilt_series', 'md_source', name='deletion_entity_type'), nullable=False),
    sa.Column('kind', sa.Enum('deletion', 'rename', name='deletion_event_kind'), nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('last_known_path', sa.String(), nullable=True),
    sa.Column('last_known_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.scan_run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deletion_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deletion_events_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_events_scan_run_id'), ['scan_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deletion_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deletion_events_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_deletion_events_sample_id'))

    op.drop_table('deletion_events')
    # ### end Alembic commands ###
