"""add reconstruction_alignment_id to issues

Revision ID: 69798d00c0ef
Revises: 4fc5ee73fa34
Create Date: 2026-08-17 18:38:51.321717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69798d00c0ef'
down_revision: Union[str, Sequence[str], None] = '4fc5ee73fa34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconstruction_alignment_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('reconstruction_alignment_id')

    # ### end Alembic commands ###
