"""add md_run_id to issues

Revision ID: 72e3bbb2df2a
Revises: 649ac31f8a2f
Create Date: 2026-07-09 14:33:18.728191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e3bbb2df2a'
down_revision: Union[str, Sequence[str], None] = '649ac31f8a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('md_run_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_issues_md_run_id'), ['md_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_md_run_id'))
        batch_op.drop_column('md_run_id')

    # ### end Alembic commands ###
