"""baseline

Revision ID: f8401280a106
Revises: 
Create Date: 2026-07-08 17:14:35.420940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8401280a106'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_root', sa.String(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.CheckConstraint('id = 1', name='catalog_meta_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', name='issue_severity'), nullable=False),
    sa.Column('scope', sa.Enum('sample', 'acquisition', 'run', name='issue_scope'), nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=True),
    sa.Column('acquisition_id', sa.String(), nullable=True),
    sa.Column('file_kind', sa.Enum('sample_toml', 'acquisition_toml', 'md_run_toml', 'mdoc', 'mrc_header', 'zarr_attrs', 'frames', 'filesystem', 'other', name='issue_file_kind'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.Float(), nullable=False),
    sa.Column('first_seen_run_id', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.Float(), nullable=False),
    sa.Column('last_seen_run_id', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.Float(), nullable=True),
    sa.Column('resolved_run_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index('ix_issues_resolved_severity', ['resolved_at', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_severity'), ['severity'], unique=False)

    op.create_table('samples',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('data_source', sa.Enum('experimental', 'simulation', name='datasource'), nullable=False),
    sa.Column('project', sa.Enum('chromatin', 'synapse', 'nanogold', name='project'), nullable=False),
    sa.Column('lab_name', sa.Enum('collepardo', 'gouaux', 'rosen', 'villa', name='labname'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('cell_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.Float(), nullable=True),
    sa.Column('disk_size_bytes', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('scan_runs',
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('ended_at', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='scan_run_status'), nullable=False),
    sa.Column('root', sa.String(), nullable=False),
    sa.Column('n_upserted', sa.Integer(), nullable=True),
    sa.Column('n_skipped', sa.Integer(), nullable=True),
    sa.Column('n_failed', sa.Integer(), nullable=True),
    sa.Column('n_new_issues', sa.Integer(), nullable=True),
    sa.Column('n_resolved_issues', sa.Integer(), nullable=True),
    sa.Column('n_warning_active', sa.Integer(), nullable=True),
    sa.Column('n_error_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('scan_run_id')
    )
    op.create_table('acquisition_scan_status',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('last_scanned_at', sa.Float(), nullable=False),
    sa.Column('last_changed_at', sa.Float(), nullable=True),
    sa.Column('last_outcome', sa.Enum('upserted', 'skipped', 'failed', name='acquisition_scan_outcome'), nullable=False),
    sa.Column('last_scan_run_id', sa.String(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('thumbnail_source_kind', sa.Enum('zarr', 'st', 'frames', 'none', name='thumbnail_source_kind'), nullable=True),
    sa.Column('thumbnail_source_path', sa.String(), nullable=True),
    sa.Column('thumbnail_generated_at', sa.Float(), nullable=True),
    sa.Column('thumbnail_status', sa.Enum('ok', 'missing_source', 'render_failed', name='thumbnail_status'), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id')
    )
    op.create_table('acquisitions',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('tilt_spacing', sa.Float(), nullable=True),
    sa.Column('defocus_range', sa.String(), nullable=True),
    sa.Column('energy_filter', sa.String(), nullable=True),
    sa.Column('phase_plate', sa.Boolean(), nullable=True),
    sa.Column('microscope', sa.String(), nullable=True),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('acquisition_quality', sa.Integer(), nullable=True),
    sa.Column('pixel_size', sa.Float(), nullable=True),
    sa.Column('dose_per_tilt', sa.JSON(), nullable=True),
    sa.Column('total_dose', sa.Float(), nullable=True),
    sa.Column('tilt_min', sa.Float(), nullable=True),
    sa.Column('tilt_max', sa.Float(), nullable=True),
    sa.Column('tilt_axis', sa.Float(), nullable=True),
    sa.Column('tilt_angles', sa.JSON(), nullable=True),
    sa.Column('defocus_per_image', sa.JSON(), nullable=True),
    sa.Column('date_collected', sa.Date(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('energy_filter_slit_width', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('camera', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id')
    )
    op.create_table('chromatin',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('substrate', sa.String(), nullable=True),
    sa.Column('linker_length_bp', sa.Float(), nullable=True),
    sa.Column('linker_pattern', sa.JSON(), nullable=True),
    sa.Column('linker_distribution', sa.String(), nullable=True),
    sa.Column('buffer', sa.String(), nullable=True),
    sa.Column('ptm', sa.String(), nullable=True),
    sa.Column('histone_variants', sa.String(), nullable=True),
    sa.Column('transcription_factors', sa.String(), nullable=True),
    sa.Column('nucleosome_count', sa.Integer(), nullable=True),
    sa.Column('dna_length_bp', sa.Integer(), nullable=True),
    sa.Column('nucleosome_uM', sa.Float(), nullable=True),
    sa.Column('sequence_identity', sa.String(), nullable=True),
    sa.Column('nucleosome_footprint', sa.JSON(), nullable=True),
    sa.Column('linker_length_fraction', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('extras',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_pk_json', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('entity_type', 'entity_pk_json', 'key')
    )
    with op.batch_alter_table('extras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extras_sample_id'), ['sample_id'], unique=False)

    op.create_table('fiducial',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('aunp_size_nm', sa.Float(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('catalog_number', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('concentration_value', sa.Float(), nullable=True),
    sa.Column('concentration_unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('freezing',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('grid_type', sa.String(), nullable=True),
    sa.Column('solution_type', sa.String(), nullable=True),
    sa.Column('cryoprotectant', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('planchette_size', sa.String(), nullable=True),
    sa.Column('spacer_thickness', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('labels',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label_target', sa.String(), nullable=True),
    sa.Column('aunp_type', sa.String(), nullable=True),
    sa.Column('aunp_size_nm', sa.JSON(), nullable=True),
    sa.Column('conjugation', sa.String(), nullable=True),
    sa.Column('conjugation_target', sa.String(), nullable=True),
    sa.Column('fluorophore', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'ordinal')
    )
    op.create_table('md_runs',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('md_run_id', sa.String(length=128), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('sample_time', sa.Float(), nullable=True),
    sa.Column('timestep', sa.Float(), nullable=True),
    sa.Column('computer', sa.String(), nullable=True),
    sa.Column('reference_contact', sa.String(), nullable=True),
    sa.Column('force_field_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'md_run_id')
    )
    op.create_table('milling',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('scheme', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('sample_scan_status',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('last_scanned_at', sa.Float(), nullable=False),
    sa.Column('last_changed_at', sa.Float(), nullable=True),
    sa.Column('last_outcome', sa.Enum('upserted', 'skipped', 'failed', name='sample_scan_outcome'), nullable=False),
    sa.Column('last_scan_run_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('scan_log_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='scan_log_level'), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.scan_run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_log_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_log_lines_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_log_lines_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_log_lines_scan_run_id'), ['scan_run_id'], unique=False)

    op.create_table('scan_sample_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.Enum('upserted', 'skipped', 'failed', name='scan_sample_outcome'), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.scan_run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_run_id', 'sample_id')
    )
    with op.batch_alter_table('scan_sample_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_sample_outcomes_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_sample_outcomes_scan_run_id'), ['scan_run_id'], unique=False)

    op.create_table('scan_state',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('last_scanned', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('path')
    )
    with op.batch_alter_table('scan_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_state_sample_id'), ['sample_id'], unique=False)

    op.create_table('simulation',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_type', sa.Enum('bulk', 'single_molecule', 'slab', name='datasettype'), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('annotations',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('annotation_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('target_tomogram', sa.String(length=128), nullable=True),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id', 'acquisition_id'], ['acquisitions.sample_id', 'acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id', 'annotation_id')
    )
    op.create_table('md_source',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('md_run_id', sa.String(length=128), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id', 'acquisition_id'], ['acquisitions.sample_id', 'acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id')
    )
    op.create_table('post_processed_tomograms',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('tomogram_id', sa.String(length=128), nullable=False),
    sa.Column('tilt_series_id', sa.String(length=128), nullable=True),
    sa.Column('denoising_software', sa.String(), nullable=True),
    sa.Column('ctf_software', sa.String(), nullable=True),
    sa.Column('missing_wedge_software', sa.String(), nullable=True),
    sa.Column('voxel_size', sa.Float(), nullable=True),
    sa.Column('derived_from', sa.JSON(), nullable=False),
    sa.Column('image_size_x', sa.Integer(), nullable=True),
    sa.Column('image_size_y', sa.Integer(), nullable=True),
    sa.Column('image_size_z', sa.Integer(), nullable=True),
    sa.Column('mrc_path', sa.String(), nullable=True),
    sa.Column('zarr_path', sa.String(), nullable=True),
    sa.Column('zarr_axes', sa.String(), nullable=True),
    sa.Column('zarr_scale', sa.JSON(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id', 'acquisition_id'], ['acquisitions.sample_id', 'acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id', 'tomogram_id')
    )
    op.create_table('raw_tomograms',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('tomogram_id', sa.String(length=128), nullable=False),
    sa.Column('tilt_series_id', sa.String(length=128), nullable=True),
    sa.Column('pipeline', sa.String(), nullable=True),
    sa.Column('software', sa.String(), nullable=True),
    sa.Column('voxel_size', sa.Float(), nullable=True),
    sa.Column('derived_from', sa.JSON(), nullable=False),
    sa.Column('image_size_x', sa.Integer(), nullable=True),
    sa.Column('image_size_y', sa.Integer(), nullable=True),
    sa.Column('image_size_z', sa.Integer(), nullable=True),
    sa.Column('mrc_path', sa.String(), nullable=True),
    sa.Column('zarr_path', sa.String(), nullable=True),
    sa.Column('zarr_axes', sa.String(), nullable=True),
    sa.Column('zarr_scale', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id', 'acquisition_id'], ['acquisitions.sample_id', 'acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id', 'tomogram_id')
    )
    op.create_table('tilt_series',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('tilt_series_id', sa.String(length=128), nullable=False),
    sa.Column('derived_from', sa.String(), nullable=True),
    sa.Column('is_aligned', sa.Boolean(), nullable=True),
    sa.Column('alignment_software', sa.String(), nullable=True),
    sa.Column('alignment_method', sa.String(), nullable=True),
    sa.Column('st_path', sa.String(), nullable=True),
    sa.Column('zarr_path', sa.String(), nullable=True),
    sa.Column('alignment_files', sa.JSON(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id', 'acquisition_id'], ['acquisitions.sample_id', 'acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id', 'tilt_series_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tilt_series')
    op.drop_table('raw_tomograms')
    op.drop_table('post_processed_tomograms')
    op.drop_table('md_source')
    op.drop_table('annotations')
    op.drop_table('simulation')
    with op.batch_alter_table('scan_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_state_sample_id'))

    op.drop_table('scan_state')
    with op.batch_alter_table('scan_sample_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_sample_outcomes_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_scan_sample_outcomes_sample_id'))

    op.drop_table('scan_sample_outcomes')
    with op.batch_alter_table('scan_log_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_log_lines_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_scan_log_lines_sample_id'))
        batch_op.drop_index(batch_op.f('ix_scan_log_lines_level'))

    op.drop_table('scan_log_lines')
    op.drop_table('sample_scan_status')
    op.drop_table('milling')
    op.drop_table('md_runs')
    op.drop_table('labels')
    op.drop_table('freezing')
    op.drop_table('fiducial')
    with op.batch_alter_table('extras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extras_sample_id'))

    op.drop_table('extras')
    op.drop_table('chromatin')
    op.drop_table('acquisitions')
    op.drop_table('acquisition_scan_status')
    op.drop_table('scan_runs')
    op.drop_table('samples')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_severity'))
        batch_op.drop_index(batch_op.f('ix_issues_sample_id'))
        batch_op.drop_index('ix_issues_resolved_severity')
        batch_op.drop_index(batch_op.f('ix_issues_fingerprint'))

    op.drop_table('issues')
    op.drop_table('catalog_meta')
    # ### end Alembic commands ###
