// AUTO-GENERATED by src/schema/generate_form_fields.py — do not edit by hand.
// Regenerate: `pixi run form-fields`. Parity guarded by
// tests/test_form_fields_drift.py.

export type FormKind = 'md_run';
export type FieldInput = 'text' | 'integer' | 'number' | 'select' | 'date';

export interface FormField {
  form: FormKind;
  section: string;
  field: string; // model field name; the TOML key for non-id fields
  label: string;
  input: FieldInput;
  required: boolean;
  isId: boolean; // intended-id field: drives the placement hint, not written
  help: string;
}

export interface FormMeta {
  form: FormKind;
  title: string;
  placement: string; // hint template; {id} filled from the intended-id field
  filename: string;
}

// Shared id check (mirrors schema.py _ID_PATTERN). Thin structural guard only —
// full validation is backend-authoritative.
export const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

export const FORM_META: Record<FormKind, FormMeta> = {
  md_run: { form: 'md_run', title: 'MD run', placement: 'MdRuns/{id}/md_run.toml', filename: 'md_run.toml' },
};

export const FORM_FIELDS: FormField[] = [
  { form: 'md_run', section: 'md_run', field: 'md_run_id', label: 'Run id', input: 'text', required: true, isId: true, help: 'Folder name under MdRuns/. Sets identity; not written into the file.' },
  { form: 'md_run', section: 'md_run', field: 'seed', label: 'Seed', input: 'integer', required: false, isId: false, help: 'Random seed for the simulation run.' },
  { form: 'md_run', section: 'md_run', field: 'sample_time', label: 'Sample time', input: 'number', required: false, isId: false, help: 'Total simulated time.' },
  { form: 'md_run', section: 'md_run', field: 'timestep', label: 'Timestep', input: 'number', required: false, isId: false, help: 'Integration timestep.' },
  { form: 'md_run', section: 'md_run', field: 'computer', label: 'Computer', input: 'text', required: false, isId: false, help: 'Machine the run executed on.' },
  { form: 'md_run', section: 'md_run', field: 'reference_contact', label: 'Reference / contact', input: 'text', required: false, isId: false, help: '' },
  { form: 'md_run', section: 'md_run', field: 'force_field_version', label: 'Force field version', input: 'text', required: false, isId: false, help: '' },
];

export function fieldsFor(form: FormKind): FormField[] {
  return FORM_FIELDS.filter((f) => f.form === form);
}
