"""Codegen ``frontend/src/utils/formFields.ts`` from ``form_fields.py``.

The authored-field registry is single-sourced in Python (ADR-0002); this
script emits the TypeScript mirror the generic form renderer consumes, the way
``generate_json_schema.py`` emits ``*.schema.json``. Run whenever the registry
changes:

    pixi run form-fields

``tests/test_form_fields_drift.py`` fails if the committed file differs from a
fresh ``render()``.
"""

from __future__ import annotations

import sys
from pathlib import Path

from schema.form_fields import FORM_FIELDS, FORM_META, FORMS
from schema.schema import _ID_PATTERN

_OUT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "utils" / "formFields.ts"


def _ts_str(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render() -> str:
    kinds = sorted(FORMS)
    kind_union = " | ".join(_ts_str(k) for k in kinds)

    meta_lines = []
    for m in sorted(FORM_META, key=lambda m: m.form):
        meta_lines.append(
            f"  {m.form}: {{ form: {_ts_str(m.form)}, title: {_ts_str(m.title)}, "
            f"placement: {_ts_str(m.placement)}, filename: {_ts_str(m.filename)} }},"
        )

    field_lines = []
    for f in FORM_FIELDS:
        field_lines.append(
            "  { "
            f"form: {_ts_str(f.form)}, section: {_ts_str(f.section)}, "
            f"field: {_ts_str(f.field)}, label: {_ts_str(f.label)}, "
            f"input: {_ts_str(f.input)}, required: {str(f.required).lower()}, "
            f"isId: {str(f.is_id).lower()}, help: {_ts_str(f.help)} "
            "},"
        )

    return f"""\
// AUTO-GENERATED by src/schema/generate_form_fields.py — do not edit by hand.
// Regenerate: `pixi run form-fields`. Parity guarded by
// tests/test_form_fields_drift.py.

export type FormKind = {kind_union};
export type FieldInput = 'text' | 'integer' | 'number' | 'select' | 'date';

export interface FormField {{
  form: FormKind;
  section: string;
  field: string; // model field name; the TOML key for non-id fields
  label: string;
  input: FieldInput;
  required: boolean;
  isId: boolean; // intended-id field: drives the placement hint, not written
  help: string;
}}

export interface FormMeta {{
  form: FormKind;
  title: string;
  placement: string; // hint template; {{id}} filled from the intended-id field
  filename: string;
}}

// Shared id check (mirrors schema.py _ID_PATTERN). Thin structural guard only —
// full validation is backend-authoritative.
export const ID_PATTERN = /{_ID_PATTERN.pattern}/;

export const FORM_META: Record<FormKind, FormMeta> = {{
{chr(10).join(meta_lines)}
}};

export const FORM_FIELDS: FormField[] = [
{chr(10).join(field_lines)}
];

export function fieldsFor(form: FormKind): FormField[] {{
  return FORM_FIELDS.filter((f) => f.form === form);
}}
"""


def main(argv: list[str] | None = None) -> int:
    out = Path(argv[0]) if argv else _OUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render())
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
