"""Codegen docs/schema.md AND the frontend schemaData.ts from schema_catalog.py.

Single source of truth is schema_catalog.CATALOG. Parity guarded by
tests/test_schema_catalog_drift.py. Regenerate: `pixi run schema-docs`.
"""
from __future__ import annotations

import sys
from pathlib import Path

from schema.schema_catalog import CATALOG, CatalogEntity

_ROOT = Path(__file__).resolve().parents[2]
_MD_OUT = _ROOT / "docs" / "schema.md"
_TS_OUT = _ROOT / "frontend" / "src" / "components" / "dataOrganization" / "schema" / "schemaData.ts"

_PREAMBLE = """\
# Database Model: CryoET + AI Portal

This document enumerates every field that will be stored in the portal database, organized by entity (Sample and Acquisition, with sub-entities and processing outputs nested beneath). For each field it lists the data type and the **authoritative source**:

| Source | What it means |
|---|---|
| `sample.toml` | Researcher-authored sample-level metadata — one file at the sample root. Field definitions live in `schema.py`. Section shown in parentheses. |
| `acquisition.toml` | Researcher-authored per-acquisition parameters and processing log (`[raw_tomogram]`, `[[post_processed_tomogram]]`, `[[annotation]]` entries) — one file in each acquisition directory. Section shown in parentheses. |
| `MDOC` | Parsed from `.mdoc` files in the `Frames/` directory by `ingest_mdoc.py`. |
| `.eer` / `.tiff` | Derived from frame file extension or EER header metadata. |
| `MRC header` | Read from the `.mrc` file header on ingest. |
| `OME-Zarr .zattrs` | Read from the multiscale metadata in `.ome.zarr` arrays. |
| `directory` | Implicit from the prescribed directory structure (sample dir name, acquisition dir name, processing folder name). |
| `derived` | Computed on ingest from other DB fields (e.g., tilt range formatted string). |

Researcher-authored fields live in one of two files: sample-level metadata in `sample.toml` at the sample root, and per-acquisition parameters plus the processing log in `acquisition.toml` inside each acquisition directory. Both files are governed by `schema.py`; the section in parentheses identifies the TOML table (`[sample]`, `[chromatin]`, `[acquisition]`, `[raw_tomogram]`, `[[post_processed_tomogram]]`, etc.). Fields coming from any other source are **not** entered by researchers and are not duplicated in either TOML (no-duplication principle).

<!-- AUTO-GENERATED by src/schema/generate_schema_docs.py — do not edit by hand.
     Edit src/schema/schema_catalog.py and run `pixi run schema-docs`. -->"""


def _kind_label(kind: str) -> str:
    return "researcher authored" if kind == "authored" else "derived"


def _rows(entity: CatalogEntity) -> str:
    lines = ["| Field | Type | Source | Source Type | Notes |", "|---|---|---|---|---|"]
    for f in entity.fields:
        lines.append(
            f"| `{f.name}` | {f.type} | `{f.source}` | {_kind_label(f.kind)} | {f.notes} |"
        )
    return "\n".join(lines)


def _children(parent_key: str) -> list[CatalogEntity]:
    return [e for e in CATALOG if e.parent == parent_key]


def _md_subtree(entity: CatalogEntity, number: str, depth: int) -> list[str]:
    """Heading + field table for ``entity`` and, recursively, its children.

    ``number`` is the section label ("1a", "2b1", …); ``depth`` the heading
    level. Recursive so a grandchild (tomograms/annotations, which hang off a
    3D-alignment group rather than off the acquisition) still gets documented.
    """
    gate = entity.arm or ("chromatin only" if entity.chromatin_only else "")
    suffix = f" ({gate})" if gate else ""
    out = [
        f"\n{'#' * depth} {number}. {entity.name}{suffix} — "
        f"_{entity.cardinality}_\n",
        _rows(entity),
    ]
    for k, child in enumerate(_children(entity.key), start=1):
        # letters at depth 3 (1a, 1b), digits below (2b1, 2b2).
        label = chr(ord("a") + k - 1) if depth == 2 else str(k)
        out.extend(_md_subtree(child, f"{number}{label}", depth + 1))
    return out


def render_md() -> str:
    tops = [e for e in CATALOG if e.parent is None]
    out = [_PREAMBLE]
    for i, top in enumerate(tops, start=1):
        out.append(f"\n---\n\n## {i}. {top.name} entity\n\n_{top.cardinality}_\n")
        out.append(_rows(top))
        for j, child in enumerate(_children(top.key), start=1):
            out.extend(
                _md_subtree(child, f"{i}{chr(ord('a') + j - 1)}", 3)
            )
    return "\n".join(out) + "\n"


def _ts_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _ts_field(f) -> str:
    return (
        "        { "
        f"field: {_ts_str(f.name)}, type: {_ts_str(f.type)}, "
        f"source: {_ts_str(f.source)}, kind: {_ts_str(f.kind)}, "
        f"notes: {_ts_str(f.notes)} "
        "},"
    )


def _ts_entity(e, indent: str) -> str:
    lines = [f"{indent}{{"]
    lines.append(f"{indent}  id: {_ts_str(e.key)}, name: {_ts_str(e.name)},")
    lines.append(f"{indent}  cardinality: {_ts_str(e.cardinality)},")
    if e.arm:
        lines.append(f"{indent}  arm: {_ts_str(e.arm)},")
    if e.chromatin_only:
        lines.append(f"{indent}  chromatinOnly: true,")
    lines.append(f"{indent}  fields: [")
    lines.extend(_ts_field(f) for f in e.fields)
    lines.append(f"{indent}  ],")
    kids = _children(e.key)
    if kids:
        lines.append(f"{indent}  children: [")
        for k in kids:
            lines.append(_ts_entity(k, indent + "    "))
        lines.append(f"{indent}  ],")
    lines.append(f"{indent}}},")
    return "\n".join(lines)


def render_ts() -> str:
    tops = [e for e in CATALOG if e.parent is None]
    body = "\n".join(_ts_entity(e, "  ") for e in tops)
    return f"""\
// AUTO-GENERATED by src/schema/generate_schema_docs.py — do not edit by hand.
// Regenerate: `pixi run schema-docs`. Parity guarded by
// tests/test_schema_catalog_drift.py.

export type SourceKind = 'authored' | 'derived';
export type Arm = 'experimental' | 'simulation';

export interface SchemaField {{
  field: string;
  type: string;
  source: string;
  kind: SourceKind;
  notes: string;
}}

export interface SchemaEntity {{
  id: string;
  name: string;
  cardinality: string;
  arm?: Arm;
  chromatinOnly?: boolean;
  fields: SchemaField[];
  children?: SchemaEntity[];
}}

export const SCHEMA: SchemaEntity[] = [
{body}
];
"""


def main(argv: list[str] | None = None) -> int:
    _MD_OUT.write_text(render_md())
    _TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    _TS_OUT.write_text(render_ts())
    print(f"wrote {_MD_OUT}")
    print(f"wrote {_TS_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
