"""Codegen docs/schema.md AND the frontend schemaData.ts from schema_catalog.py.

Single source of truth is schema_catalog.CATALOG. Parity guarded by
tests/test_schema_catalog_drift.py. Regenerate: `pixi run schema-docs`.
"""
from __future__ import annotations

import sys
from pathlib import Path

from schema.schema_catalog import CATALOG, CatalogEntity

_ROOT = Path(__file__).resolve().parents[2]
_MD_OUT = _ROOT / "docs" / "schema.md"

_PREAMBLE = """\
# Database Model: CryoET + AI Portal

This document enumerates every field that will be stored in the portal database, organized by entity (Sample → Acquisition → Tomogram → Annotation). For each field it lists the data type and the **authoritative source**:

| Source | What it means |
|---|---|
| `sample.toml` | Researcher-authored sample-level metadata — one file at the sample root. Field definitions live in `schema.py`. Section shown in parentheses. |
| `acquisition.toml` | Researcher-authored per-acquisition parameters and processing log (`[raw_tomogram]`, `[[post_processed_tomogram]]`, `[[annotation]]` entries) — one file in each acquisition directory. Section shown in parentheses. |
| `MDOC` | Parsed from `.mdoc` files in the `Frames/` directory by `ingest_mdoc.py`. |
| `.eer` / `.tiff` | Derived from frame file extension or EER header metadata. |
| `MRC header` | Read from the `.mrc` file header on ingest. |
| `OME-Zarr .zattrs` | Read from the multiscale metadata in `.ome.zarr` arrays. |
| `directory` | Implicit from the prescribed directory structure (sample dir name, acquisition dir name, processing folder name). |
| `derived` | Computed on ingest from other DB fields (e.g., tilt range formatted string). |

Researcher-authored fields live in one of two files: sample-level metadata in `sample.toml` at the sample root, and per-acquisition parameters plus the processing log in `acquisition.toml` inside each acquisition directory. Both files are governed by `schema.py`; the section in parentheses identifies the TOML table (`[sample]`, `[chromatin]`, `[acquisition]`, `[raw_tomogram]`, `[[post_processed_tomogram]]`, etc.). Fields coming from any other source are **not** entered by researchers and are not duplicated in either TOML (no-duplication principle).

<!-- AUTO-GENERATED by src/schema/generate_schema_docs.py — do not edit by hand.
     Edit src/schema/schema_catalog.py and run `pixi run schema-docs`. -->"""


def _kind_label(kind: str) -> str:
    return "researcher authored" if kind == "authored" else "derived"


def _rows(entity: CatalogEntity) -> str:
    lines = ["| Field | Type | Source | Source Type | Notes |", "|---|---|---|---|---|"]
    for f in entity.fields:
        lines.append(
            f"| `{f.name}` | {f.type} | `{f.source}` | {_kind_label(f.kind)} | {f.notes} |"
        )
    return "\n".join(lines)


def _children(parent_key: str) -> list[CatalogEntity]:
    return [e for e in CATALOG if e.parent == parent_key]


def render_md() -> str:
    tops = [e for e in CATALOG if e.parent is None]
    out = [_PREAMBLE]
    for i, top in enumerate(tops, start=1):
        out.append(f"\n---\n\n## {i}. {top.name} entity\n\n_{top.cardinality}_\n")
        out.append(_rows(top))
        for j, child in enumerate(_children(top.key), start=1):
            gate = child.arm or ("chromatin only" if child.chromatin_only else "")
            suffix = f" ({gate})" if gate else ""
            out.append(f"\n### {i}{chr(ord('a') + j - 1)}. {child.name}{suffix} — _{child.cardinality}_\n")
            out.append(_rows(child))
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    _MD_OUT.write_text(render_md())
    print(f"wrote {_MD_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
